# Calcul matriciel et pièges en numpy

Un des principaux défauts de ```numpy``` (par rapport à des environnement comme Matlab par exemple) est la **différentiation entre les vecteurs et les matrices**... Cet aspect va poser de nombreux problèmes.

Le second défaut réside dans le **dispatch dynamique**: python essaie de faire marcher les calculs, même quand les dimensions des matrices sont incompatibles... Ca fait gagner un peu de temps parfois... Et ça crée des bugs insurmontables d'autres fois.


**Rappel:**

Pour executer une cellule : Shift + Entrée

**Exercices** (marqués <span style="color:red"> EXO</span>) Des exercices sont proposés régulièrement dans le notebook pour éviter *l'effet contemplatif* des exemples. Si vous maitrisez déjà les concepts de base et que les solutions vous semblent évidentes, n'héstiez pas à sauter des questions.

Tous les exercices sont classés par ordre d'importance:  <span style="color:red"> 1</span>="essentiel", <span style="color:red">2</span>="utile, <span style="color:red">3</span>="optionnel et/ou avancé"

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Produit matriciel

Il ne faut pas confondre le produit terme à terme, entre matrices de mêmes dimensions et le produit matriciel qui est un ensemble de produits scalaires. 
Dans le produit matriciel, le nombre de colonne de la première matrice doit correspondre au nombre de ligne de la seconde/


<img src="./ressources/matrix_mult.png" width="200px">

$$ {\color {red}c_{{12}}}=\sum _{{r=1}}^{2}a_{{1r}}b_{{r2}}=a_{{11}}b_{{12}}+a_{{12}}b_{{22}}$$

$$ {\color {blue}c_{{33}}}=\sum _{{r=1}}^{2}a_{{3r}}b_{{r3}}=a_{{31}}b_{{13}}+a_{{32}}b_{{23}}$$

In [5]:
A = np.array([[0., 1], [2, 3], [4, 5], [6, 7]])
B = np.array([[5., 4, 3], [2, 1, 0]])
print("A=",A,"\n B=",B)
print('\n')

# calcul de produit matriciel, par différents moyens
C  = A@B # le plus clair (d'après moi)
C2 = A.dot(B)

print(C)
print('\n')
print(C2)

A= [[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]] 
 B= [[5. 4. 3.]
 [2. 1. 0.]]


[[ 2.  1.  0.]
 [16. 11.  6.]
 [30. 21. 12.]
 [44. 31. 18.]]


[[ 2.  1.  0.]
 [16. 11.  6.]
 [30. 21. 12.]
 [44. 31. 18.]]


In [6]:
# test sur des matrices incompatibles (matriciel)
# le nombre de colonne de A doit être égal au nombre de ligne de B

A = np.array([[0., 1], [2, 3], [4, 5], [6, 7]])
M = np.array([[0., 1], [2, 3], [4, 5]])

print(A@M) # matriciel

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [7]:
# et le produit terme à terme, uniquement entre matrices de même dimension

print(A*M) # terme à terme

ValueError: operands could not be broadcast together with shapes (4,2) (3,2) 

In [11]:
# et le produit terme à terme, uniquement entre matrices de même dimension
# cas correct

A = np.array([[0., 1], [2, 3], [4, 5], [6, 7]])
A2 = np.array([[1., 2], [2, 1], [1, 2], [2, 1]])

print(A*A2)
print('\n')
print(A@A2.T)

[[ 0.  2.]
 [ 4.  3.]
 [ 4. 10.]
 [12.  7.]]


[[ 2.  1.  2.  1.]
 [ 8.  7.  8.  7.]
 [14. 13. 14. 13.]
 [20. 19. 20. 19.]]


In [12]:
# test sur des données incompatibles (terme à terme)

C3 = A*B # Comprendre le message d'erreur (il va être récurrent !)

ValueError: operands could not be broadcast together with shapes (4,2) (2,3) 

### <span style="color:red"> EXO (3) reprogrammer la multiplication matricielle </span>

[plutot pour les étudiants qui ne sont pas familier avec le produit matriciel]
1. Dessiner les matrice au brouillon
2. Algo en 3 boucles à identifier

In [13]:
# soit les matrices (compatibles)
A = np.array([[0., 1], [2, 3], [4, 5], [6, 7]])
B = np.array([[5., 4, 3], [2, 1, 0]])

# fonction de calcul matricielle
def calc_mat(a, b):
    # Construire la matrice c, résultat de la multiplication matricielle de a par b
    # Construction "à la main", avec trois boucles for
    #  TODO 

# test
print("REFERENCE")
print(A@B)
print("NOUVELLE FONCTION")
print(calc_mat(A,B))

IndentationError: expected an indented block after function definition on line 6 (4039622793.py, line 12)

## Types de données

In [ ]:
# Les commandes ci-dessous créent des vecteurs

v1=np.random.rand(10)
v2=np.array([1, 4, 18])
v3=np.ones(12)

print(v1.shape, v2.shape, v3.shape)

v1=np.random.rand(10,1) #crée bien des matrices colonnes ou lignes
v2=np.array([[1, 4, 18]])
v3=np.ones((12,1))

print(v1.shape, v2.shape, v3.shape)

(10,) (3,) (12,)
(10, 1) (1, 3) (12, 1)


In [20]:
# Les commandes ci-dessous créent des matrices

m1=np.random.rand(10,2)
m2=np.array([[1, 4, 18],[2, 4, 6]])
m3=np.ones((12,2))

print(m1.shape)

(10, 2)


In [22]:
# Cas limite
# attention, ces deux objets ne vont pas avoir le même comportement selon les fonctions utilisées

v2 = np.array([1, 4, 18])
# et 
m2 = np.array([[1, 4, 18]])

print("v2 et m2 ne sont pas du même type: ", v2.shape, m2.shape)

tv2 = np.ones((3, 3))@v2
print(tv2) # il prend le vecteur en colonne => OK
tv2_bis = v2@np.ones((3, 3))
print(tv2_bis) # il prend le vecteur en ligne => OK
tm2 = np.ones((3, 3))@m2
print(tm2) # les dimensions sont incompatibles (pas de degré de liberté quand les dimensions sont fixées)


v2 et m2 ne sont pas du même type:  (3,) (1, 3)
[23. 23. 23.]
[23. 23. 23.]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [23]:
# extraire une ligne ou une colonne => générer un vecteur (et pas une matrice)
# => nous sommes obligé de jongler avec les types de données

m1 = np.random.rand(10,3)
v4 = m1[:,1]   # extraction d'une colonne => vecteur
m4 = m1[:,1:3] # extraction de deux colonnes => matrice
x1 = m1[:,1:2] # extraction d'une seule colonnes, mais en syntaxe matricielle => ???

print(v4.shape, m4.shape)
print(x1.shape) # => matrice !!

(10,) (10, 2)
(10, 1)


### Pourquoi ces différences de types posent problème?

In [24]:
# Definition de 3 versions de B

A     = np.array([[0., 1], [2, 3], [4, 5], [6, 7]])
B_col = np.array([[1.], [2]]) # matrice (=en forme de vecteur colonne)
B_li  = np.array([[1., 2]])   # matrice (=en forme de vecteur ligne)
B_vec = np.array([1., 2])     # vecteur


In [ ]:

# les cas qui marchent
print(A@B_col)
print(A@B_vec) # les résultats n'ont pas les mêmes dimensions
print(A.dot(B_col))
print(A.dot(B_vec)) # les résultats n'ont pas les mêmes dimensions

print("\n")

# 
print(A, B_li)
print('\n')
print(A*B_li)    # Catastrophe => ca ne fait pas d'erreur
print(A*B_vec)   # Catastrophe => ca ne fait pas d'erreur

[[ 2.]
 [ 8.]
 [14.]
 [20.]]
[ 2.  8. 14. 20.]
[[ 2.]
 [ 8.]
 [14.]
 [20.]]
[ 2.  8. 14. 20.]


[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]] [[1. 2.]]


[[ 0.  2.]
 [ 2.  6.]
 [ 4. 10.]
 [ 6. 14.]]
[[ 0.  2.]
 [ 2.  6.]
 [ 4. 10.]
 [ 6. 14.]]


In [28]:
# les cas qui ne marchent pas (1)
print(A@B_li) # KO pour les dimensions => raisonnable, mais attention aux versions de python


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

In [29]:
# les cas qui ne marchent pas (2)

print(A*B_col) # Erreur => c'est logique

ValueError: operands could not be broadcast together with shapes (4,2) (2,1) 

In [33]:
B_col = np.array([[1.], [2]]) # matrice (=en forme de vecteur colonne)
B_li  = np.array([[1., 2]])   # matrice (=en forme de vecteur ligne)
B_vec = np.array([1., 3])     #

print(B_li@B_col) # le calcul est propre... Et renvoie une matrice
# print(B_li@B_li)  # KO
print(B_vec@B_vec) # produit scalaire
print(B_vec@B_col) # renvoie un vecteur


[[5.]]
10.0
[7.]


In [34]:
# tentons dans l'autre sens
# 
print(B_col @ B_li) # renvoie une matrice (OK)
# print(B_col @ B_vec) # KO : alors qu'on  voudrait intuitivement que ça marche
print(B_vec * B_li) # OK
print(B_vec * B_col) # => WAOUH , carrement n'importe quoi !!

[[1. 2.]
 [2. 4.]]
[[1. 6.]]
[[1. 3.]
 [2. 6.]]


## Dispatch dynamique

Beaucoup de comportements étranges sont liés à cette fonctionnalité. Partons d'un exemple simple et étudions les différentes solutions pratiques:

    # Soit la matrice A:
    A = np.array([[0., 1], [2, 3], [4, 5], [6, 7]])
    # Je souhaite multiplier chaque ligne par le vecteur [1,2]

In [36]:
# Soit la matrice A:
A = np.array([[0., 1], [2, 3], [4, 5], [6, 7]])

# Je souhaite multiplier chaque ligne par le vecteur [1,2]


In [37]:
# solution 1: developpeur standard avec des boucles

B = A.copy()
for ligne in B:
    ligne *= [1,2]
print(B)

[[ 0.  2.]
 [ 2.  6.]
 [ 4. 10.]
 [ 6. 14.]]


In [38]:
# solution 2: raisonnement matriciel, je veux juste multiplier la seconde colonne par un scalaire
B = A.copy()
B[:,1] *= 2
print(B)

[[ 0.  2.]
 [ 2.  6.]
 [ 4. 10.]
 [ 6. 14.]]


In [39]:
# solution 3: je crée une matrice pour ensuite faire une multiplication terme à terme

M = np.ones((4,2))
M[:,1] *= 2
B = A*M
print(B)

[[ 0.  2.]
 [ 2.  6.]
 [ 4. 10.]
 [ 6. 14.]]


In [40]:
# solution 4: dispatch dynamique
# ça ne devrait pas marcher... MAIS
#   1. python détecte que le nb de colonne est compatible
#   2. python applique l'opération sur chaque ligne automatiquement
#   => pratique... Mais risqué: il faut connaitre ce truc pour détecter les bugs associés

B = A * [1,2]
print(B)

[[ 0.  2.]
 [ 2.  6.]
 [ 4. 10.]
 [ 6. 14.]]


In [41]:
# pour faire la même chose sur les colonnes
# à multiplier par [1, 2, 3, 4]

B = A * [[1],[2],[3],[4]] # il faut présenter un vecteur colonne pour que python accepte le dispatch
print(B)

[[ 0.  1.]
 [ 4.  6.]
 [12. 15.]
 [24. 28.]]


## <span style="color:red"> EXO produit divers</span>

Soit une matrice de dimension $(n,d)$ remplie de 1. Chercher la formule qui permet de passer à une matrice $[1,2,...,d]$ répété respectivement sur les lignes ou les colonnes:

$ M = \begin{pmatrix}
1 & 1 & \ldots &1 \\
1 & 1 & \ldots & 1 \\
\vdots &  \vdots & \ddots & \vdots \\
1 & 1 & \ldots & 1 \\
\end{pmatrix} 
\Rightarrow 
\begin{pmatrix}
1 & 2 & \ldots &d \\
1 & 2 & \ldots & d \\
\vdots &  \vdots & \ddots & \vdots \\
1 & 2 & \ldots & d \\
\end{pmatrix} \text{ ou }
\begin{pmatrix}
1 & 1 & \ldots &1 \\
2 & 2 & \ldots & 2 \\
\vdots &  \vdots & \ddots & \vdots \\
n & n & \ldots & n \\
\end{pmatrix}$

In [ ]:
def f_ligne(n,d):
    M = np.ones((n,d))
    for k in range(d-1):
        M[:,k+1] += M[:,k]
    return M 

def f_col(n,d):
    M = np.ones((n,d))
    for k in range(n-1):
        M[k+1,:] += M[k,:]
    return M 

print(f_ligne(5,6))
print('\n')
print(f_col(5,6))
print('\n')

###

M_col = np.array([[i+1 for i in range(6)] for j in range(5)])
M_ligne = np.array([[j+1 for i in range(6)] for j in range(5)])

print(M_col)
print('\n')
print(M_ligne)

[[1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]]


[[1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5.]]


[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


[[1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [3 3 3 3 3 3]
 [4 4 4 4 4 4]
 [5 5 5 5 5 5]]


## <span style="color:red"> EXO Evaluation d'une fonction linéaire</span>

Soit une matrice $X$ de dimension $(n,d)$ stockant $n$ échantillon $\mathbf x_i \in \mathbb R^d$ et un vecteur de paramètres $w \in \mathbb R^d$, 

$ X = \begin{pmatrix}
x_{11} & x_{12} & \ldots & x_{1d} \\
x_{21} & x_{22} & \ldots & x_{2d} \\
\vdots &  \vdots & \ddots & \vdots \\
x_{n1} & x_{n2} & \ldots & x_{nd} \\
\end{pmatrix} 
\qquad
W = \begin{pmatrix}
w_{1} & w_{2} & \ldots & w_{d} 
\end{pmatrix} 
$

Calculer l'ensemble : $\forall i, f(\mathbf x_i) = \sum_{j=1}^d x_{ij} w_j $
Cet ensemble sera stocké dans un vecteur.

In [ ]:
n = 100
d = 10
X = np.random.rand(n,d)
W = np.arange(d)

Y = X@W
print(Y)

(10,)
[16.01513293 16.41366522 25.62917365 22.55804411 30.53514277 16.2418662
 25.76064356 16.02743295 25.57735778 15.7557089  26.27992686 30.88145641
 29.72543748 17.99605627 21.37239514 15.3257957  13.21048453 28.52899443
  8.91888702 22.65930379 23.2734497  22.47154395 26.27773572 29.15141676
 16.11467804 23.79313093 30.14453215 25.04930677 21.79452757 26.65272567
 22.56320141 24.36337077 16.17875031 24.12005098 24.72512648 20.71049955
 16.1887418  33.6157836  20.29587747 14.69159548 15.87479472 21.82511232
 20.70151761 24.7545665  24.63408053 20.37996937 24.72964014 28.78635391
 15.07328112 16.87925607 19.59624473 29.41542638 17.73011083 17.49149364
 26.42337284 20.96330981 28.93296031 19.5716499  13.32664372 19.86335254
 29.34597471 19.52750003 25.42751108 29.07260551 18.74306584 21.31596439
 17.77810123 16.43797889 26.25085924 28.44240124 21.36203123 12.75957197
 27.9852124  24.63075483 19.0411487  16.76442134 33.28682631 31.01240894
 18.20550667 25.54924155 18.82015505 20.670274

# Construction du sujet à partir de la correction

In [ ]:
###  TODO )"," TODO ",\
    txt, flags=re.DOTALL))
f2.close()

### </CORRECTION> ###